export const heroImages = {
  ana: 'https://i.postimg.cc/66cgrVpB/ana.webp',
  ashe: 'https://i.postimg.cc/hjbw3T8b/ashe.webp',
  baptiste: 'https://i.postimg.cc/Pxk942D5/baptiste.webp',
  bastion: 'https://i.postimg.cc/rppNLWLN/bastion.webp', 
  brigitte: 'https://i.postimg.cc/VNt2n3dh/brigitte.webp',
  cassidy: 'https://i.postimg.cc/rwjNbj7p/cassidy.webp',
  dva: 'https://i.postimg.cc/P59BLtrZ/d-va.webp',
  doomfist: 'https://i.postimg.cc/Nj53fyYB/doomfist.webp',
  echo: 'https://i.postimg.cc/4NLCg6DW/echo.webp',
  genji: 'https://i.postimg.cc/kXXrz1pV/genji.webp',
  hanzo: 'https://i.postimg.cc/J7QVTVPV/hanzo.webp',
  illari: 'https://i.postimg.cc/hvskhTfP/illari.webp',
  junkerqueen: 'https://i.postimg.cc/Fzht9DFB/junkerqueen.webp',
  junkrat: 'https://i.postimg.cc/RF755jmt/junkrat.webp',
  kiriko: 'https://i.postimg.cc/RF55Yvk9/kiriko.webp',
  lifeweaver: 'https://i.postimg.cc/vm6wX4S3/lifeweaver.webp',
  lucio: 'https://i.postimg.cc/2Stf4QT1/lucio.webp',
  mauga: 'https://i.postimg.cc/y8xHgQhq/mauga.webp',
  mei: 'https://i.postimg.cc/h48gH74Y/mei.webp',
  mercy: 'https://i.postimg.cc/dtqvvtLV/mercy.webp',
  moira: 'https://i.postimg.cc/65YKQJvL/moira.webp',
  orisa: 'https://i.postimg.cc/XqgbFtDW/orisa.webp',
  pharah: 'https://i.postimg.cc/j2TTDRcv/pharah.webp',
  ramattra: 'https://i.postimg.cc/26hmj1QV/ramattra.webp',
  reaper: 'https://i.postimg.cc/Bvd4GT1r/reaper.webp',
  reinhardt: 'https://i.postimg.cc/yxLG7KbD/reinhardt.webp',
  roadhog: 'https://i.postimg.cc/9FfSJ4DZ/roadhog.webp',
  sigma: 'https://i.postimg.cc/xTFZ70m7/sigma.webp',
  sojourn: 'https://i.postimg.cc/qvhFH9X7/sojourn.webp',
  soldier76: 'https://i.postimg.cc/25nXVhtR/soldier.webp',
  sombra: 'https://i.postimg.cc/g2CTzNNH/sombra.webp',
  symmetra: 'https://i.postimg.cc/PxhVZNGL/symmetra.webp',
  torbjorn: 'https://i.postimg.cc/6pvMmCt2/torbjorn.webp',
  tracer: 'https://i.postimg.cc/ydPQTBBL/tracer.webp',
  venture: 'https://i.postimg.cc/J0zT6gzM/venture.webp',
  widowmaker: 'https://i.postimg.cc/Y0DdJ3vg/widowmaker.webp',
  winston: 'https://i.postimg.cc/DfxpJ2xZ/winston.webp',
  wreckingball: 'https://i.postimg.cc/3J6L1t5Q/wreckingball.webp',
  zarya: 'https://i.postimg.cc/154CDLdK/zarya.webp',
  zenyatta: 'https://i.postimg.cc/PqnSsN56/zenyatta.webp',
  juno: 'https://i.postimg.cc/BbSyWbMW/juno.webp',
};

export default heroImages;
