export const heroImages = {
    ana: 'https://i.postimg.cc/T3GHsYCK/ana.png',
    ashe: 'https://i.postimg.cc/pXK6knYN/ashe.png',
    baptiste: 'https://i.postimg.cc/7PFRgNzM/baptiste.png',
    bastion: 'https://i.postimg.cc/CMBtB2Rx/bastion.png',
    brigitte: 'https://i.postimg.cc/WzkfBdBk/brigitte.png',
    cassidy: 'https://i.postimg.cc/tTfMv3Mb/cassidy.png',
    dva: 'https://i.postimg.cc/Y9jPxn88/d-va.png',
    doomfist: 'https://i.postimg.cc/hG2wTW8f/doomfist.png',
    echo: 'https://i.postimg.cc/0NkFz2wT/echo.png',
    genji: 'https://i.postimg.cc/YCfT2mhN/genji.png',
    hanzo: 'https://i.postimg.cc/wjdSdkTT/hanzo.png',
    illari: 'https://i.postimg.cc/9F9vSk2n/illari.png',
    junkerqueen: 'https://i.postimg.cc/XNmRsbR5/junkerqueen.png',
    junkrat: 'https://i.postimg.cc/FFYtbRBm/junkrat.png',
    kiriko: 'https://i.postimg.cc/QC2J1SnB/kiriko.png',
    lifeweaver: 'https://i.postimg.cc/Kjk51CQS/lifeweaver.png',
    lucio: 'https://i.postimg.cc/TwH9YTVJ/lucio.png',
    mauga: 'https://i.postimg.cc/hjGsBXdG/mauga.png',
    mei: 'https://i.postimg.cc/rpjj31zb/mei.png',
    mercy: 'https://i.postimg.cc/mrBVmXZC/mercy.png',
    moira: 'https://i.postimg.cc/Mpydb2wz/moira.png',
    orisa: 'https://i.postimg.cc/bwXmtYK6/orisa.png',
    pharah: 'https://i.postimg.cc/L6gy5g0Y/pharah.png',
    ramattra: 'https://i.postimg.cc/wxGf9QFY/ramattra.png',
    reaper: 'https://i.postimg.cc/wMZ0F93j/reaper.png',
    reinhardt: 'https://i.postimg.cc/1Xfvp8md/reinhardt.png',
    roadhog: 'https://i.postimg.cc/wvWWyXpJ/roadhog.png',
    sigma: 'https://i.postimg.cc/1tRC3WLs/sigma.png',
    sojourn: 'https://i.postimg.cc/s24HyFHT/sojourn.png',
    soldier76: 'https://i.postimg.cc/HLgvfWzJ/soldier.png',
    sombra: 'https://i.postimg.cc/4xtFLH6k/sombra.png',
    symmetra: 'https://i.postimg.cc/CL9Qssfs/symmetra.png',
    torbjorn: 'https://i.postimg.cc/dthfCxD0/torbjorn.png',
    tracer: 'https://i.postimg.cc/c19jrSxj/tracer.png',
    venture: 'https://i.postimg.cc/L5b07zQR/venture.png',
    widowmaker: 'https://i.postimg.cc/XqJzQ28Q/widowmaker.png',
    winston: 'https://i.postimg.cc/bJqM2Y2X/winston.png',
    wreckingball: 'https://i.postimg.cc/W3SymRMd/wreckingball.png',
    zarya: 'https://i.postimg.cc/3wXVR0NC/zarya.png',
    zenyatta: 'https://i.postimg.cc/d0PgwjsV/zenyatta.png',
    juno: 'https://i.postimg.cc/rpwZ8Z6c/juno.png',
  };

  export default heroImages;